[package]
name = "network_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
easy-threadpool = "0.3.2"
paste = "1.0.14"
